---
- name: Install and configure NIS (ypbind) and autofs
  hosts: localhost
  become: true
  gather_facts: yes

  tasks:

    # --- PACKAGE INSTALLATION BASED ON OS FAMILY ---

    - name: Install packages on RedHat family
      package:
        name:
          - ypbind
          - autofs
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install packages on Debian family
      apt:
        name:
          - nis
          - autofs
        state: present
        update_cache: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install packages on SUSE family
      zypper:
        name:
          - ypbind
          - autofs
        state: present
      when: ansible_facts['os_family'] == "SUSE"

    # --- MANAGED CONFIGURATION FILES ---

    - name: Deploy /etc/nsswitch.conf
      copy:
        src: files/nsswitch.conf
        dest: /etc/nsswitch.conf
        owner: root
        group: root
        mode: '0644'
        force: yes

    - name: Deploy /etc/yp.conf
      copy:
        src: files/yp.conf
        dest: /etc/yp.conf
        owner: root
        group: root
        mode: '0644'
        force: yes

    - name: Deploy /etc/defaultdomain
      copy:
        src: files/defaultdomain
        dest: /etc/defaultdomain
        owner: root
        group: root
        mode: '0644'
        force: yes

    # --- RESTART AND ENABLE SERVICES ---

    - name: Restart and enable ypbind and autofs
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - ypbind
        - autofs
