---
- name: Overwrite /etc/nsswitch.conf
  hosts: localhost
  become: yes
  tasks:
    - name: Replace /etc/nsswitch.conf with managed copy
      copy:
        src: files/nsswitch.conf
        dest: /etc/nsswitch.conf
        owner: root
        group: root
        mode: '0644'
        force: yes
    - name: Replace /etc/yp.conf with managed copy
      copy:
        src: files/yp.conf
        dest: /etc/yp.conf
        owner: root
        group: root
        mode: '0644'
        force: yes


    - name: Restart ypbind and autofs services
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - ypbind
        - autofs


